#!/usr/bin/env bash
# Select the game engine for this repo (npm run engine).
#
#   npm run engine                          show the current engine
#   npm run engine -- <engine>              switch to phaser | three | babylon | none
#   npm run engine -- <engine> --starter    ...and replace src/scripts/app/ (+ tools/capture/autopilot.cjs)
#                                           with that engine's starter sample (OVERWRITES your app code)
#   npm run engine -- all                   template maintenance: install every engine and typecheck
#                                           all engine code plus the starters
#
# Engine packages are NOT in package.json by default, so a Phaser game never
# installs Babylon. Switching does three things:
#   1. npm uninstall the other engines' packages, npm install the chosen one's
#   2. regenerate tsconfig.engine.json so `npm run typecheck` skips the
#      src/scripts/{core,utilities}/<other engine>/ code (vite only bundles
#      what src/main.ts imports, so only typecheck needs this)
#   3. record the choice in package.json "config.engine"
# The starter is applied automatically while src/scripts/app/ is still an
# untouched starter (fresh clone / placeholder); once it has your own code you
# must pass --starter explicitly.
#
# Starters live in tools/template/starters/<engine>/ and mirror the repo root.
# Compatible with the macOS system bash (3.2).
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$here" rev-parse --show-toplevel)"
STARTERS="$here/starters"
ENGINES="phaser three babylon"
# Paths a starter owns; replaced wholesale when a starter is applied.
STARTER_PATHS="src/scripts/app tools/capture/autopilot.cjs"
TSCONFIG_ENGINE="tsconfig.engine.json"

cd "$REPO_ROOT"

engine_packages() {
  case "$1" in
    phaser)  echo "phaser@^3.90.0" ;;
    three)   echo "three@^0.186.0 @dimforge/rapier3d-compat@^0.21.0" ;;
    babylon) echo "@babylonjs/core@^8.26.0 @babylonjs/gui@^8.26.0 @babylonjs/loaders@^8.26.0 @babylonjs/havok@^1.3.10" ;;
  esac
}
engine_dev_packages() {
  case "$1" in
    three) echo "@types/three@^0.186.0" ;;
  esac
}
# "name@spec" -> "name" (also for scoped packages)
pkg_name() { printf '%s\n' "${1%@*}"; }

is_engine() { case " $ENGINES " in *" $1 "*) return 0 ;; esac; return 1; }

current_engine() {
  node -p 'const p = require("./package.json"); (p.config && p.config.engine) || "none"'
}
has_package() {
  node -e 'const p = require("./package.json"); const n = process.argv[1];
           process.exit((p.dependencies || {})[n] || (p.devDependencies || {})[n] ? 0 : 1)' "$1"
}

show() {
  echo "engine: $(current_engine)"
  local e spec name
  for e in $ENGINES; do
    for spec in $(engine_packages "$e") $(engine_dev_packages "$e"); do
      name="$(pkg_name "$spec")"
      if has_package "$name"; then echo "  installed: $name ($e)"; fi
    done
  done
  echo "switch: npm run engine -- <$(echo "$ENGINES" | tr ' ' '|')|none|all> [--starter]"
}

# Engines whose packages/code are active for a target.
selected_engines() {
  case "$1" in
    all)  echo "$ENGINES" ;;
    none) echo "" ;;
    *)    echo "$1" ;;
  esac
}

write_tsconfig() {
  local target="$1" sel="$2" e inc exc=""
  inc='"src"'
  [[ "$target" == "all" ]] && inc='"src", "tools/template/starters"'
  for e in $ENGINES; do
    case " $sel " in *" $e "*) continue ;; esac
    exc="$exc${exc:+, }\"src/scripts/core/$e\", \"src/scripts/utilities/$e\""
  done
  cat > "$TSCONFIG_ENGINE" <<TSEOF
// Generated by tools/template/engine.sh (npm run engine -- $target). Do not edit by hand.
// tsconfig.json extends this file; it only decides what \`npm run typecheck\` sees.
{
  "include": [$inc],
  "exclude": [$exc]
}
TSEOF
}

# True while src/scripts/app matches one of the starters exactly (or is missing).
app_is_pristine() {
  [[ -d src/scripts/app ]] || return 0
  local d
  for d in "$STARTERS"/*/; do
    [[ -d "$d/src/scripts/app" ]] || continue
    if diff -rq "$d/src/scripts/app" src/scripts/app >/dev/null 2>&1; then return 0; fi
  done
  return 1
}

apply_starter() {
  local e="$1" src="$STARTERS/$1" p f
  if [[ ! -d "$src" ]]; then
    echo "no starter for '$e' (tools/template/starters/$e): src/scripts/app left as is"
    return 0
  fi
  for p in $STARTER_PATHS; do rm -rf -- "$p"; done
  while IFS= read -r f; do
    f="${f#./}"
    mkdir -p "$(dirname "$f")"
    cp "$src/$f" "$f"
  done < <(cd "$src" && find . -type f -not -name .DS_Store)
  echo "starter '$e' applied to: $(echo "$STARTER_PATHS" | sed 's/ /, /g')"
}

# ---------------------------------------------------------------- main
target="${1:-}"
starter=0
if (( $# > 0 )); then shift; fi
for a in "$@"; do
  case "$a" in
    --starter) starter=1 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done
if [[ -z "$target" ]]; then show; exit 0; fi
if [[ "$target" != "none" && "$target" != "all" ]] && ! is_engine "$target"; then
  echo "error: unknown engine '$target' (phaser | three | babylon | none | all)" >&2
  exit 2
fi
sel="$(selected_engines "$target")"

# 1. packages
remove="" add="" add_dev=""
for e in $ENGINES; do
  case " $sel " in
    *" $e "*)
      add="$add $(engine_packages "$e")"
      add_dev="$add_dev $(engine_dev_packages "$e")"
      ;;
    *)
      for spec in $(engine_packages "$e") $(engine_dev_packages "$e"); do
        name="$(pkg_name "$spec")"
        if has_package "$name"; then remove="$remove $name"; fi
      done
      ;;
  esac
done
if [[ -n "${remove// /}" ]]; then
  echo "npm uninstall" $remove
  npm uninstall --no-fund --no-audit $remove
fi
if [[ -n "${add// /}" ]]; then
  echo "npm install" $add
  npm install --no-fund --no-audit $add
fi
if [[ -n "${add_dev// /}" ]]; then
  echo "npm install -D" $add_dev
  npm install -D --no-fund --no-audit $add_dev
fi

# 2. typecheck scope
write_tsconfig "$target" "$sel"
echo "wrote $TSCONFIG_ENGINE"

# 3. record the choice
npm pkg set config.engine="$target"

# 4. starter
if [[ "$target" != "all" ]]; then
  if (( starter )) || app_is_pristine; then
    apply_starter "$target"
  else
    echo "src/scripts/app/ has your own code: left as is (it may still import the previous engine;"
    echo "  pass --starter to replace it with the '$target' starter)"
  fi
fi

echo
echo "engine: $target"
echo "next: npm run dev / npm run typecheck"
